name: neuro_companion
description: A lightweight mental wellness assistant.
version: 1.0.0+1
environment:
  sdk: ">=2.17.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.0
  path_provider: ^2.1.2
  share_plus: ^7.0.0
  speech_to_text: ^6.3.0
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true


# Added Azure dependencies
dependencies:
  flutter_riverpod: ^2.4.0
  firebase_crashlytics: ^3.3.3
  azure_storage_blobs: ^0.11.0
  azure_identity: ^0.1.0
